---
version: 2.1

commands:
  s3deploy:
    description: "Deploy to S3"
    parameters:
      to:
        type: string
      cf_distribution_id:
        type: string
      dir:
        type: string
    steps:
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          aws s3 sync << parameters.dir >> s3://<< parameters.to >> \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          aws cloudfront create-invalidation \
              --distribution-id << parameters.cf_distribution_id >> \
              --paths /\*

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.13.1-browsers

aliases:
  - &login-to-registry |
    npm config set @codeyourfuture:registry https://npm.pkg.github.com/codeyourfuture
    echo "//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGES_TOKEN" > ~/repo/.npmrc

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run linting
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn test

  build_storybook:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - attach_workspace:
          at: .
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build storybook app
          command: yarn build-storybook
      - persist_to_workspace:
          root: .
          paths: .

  build:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - attach_workspace:
          at: .
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build Package
          command: yarn babel:build
      - persist_to_workspace:
          root: .
          paths: .

  deploy_storybook:
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/repo
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - s3deploy:
          to: ui.codeyourfuture.io
          cf_distribution_id: EDEUWC1FIFMFD
          dir: /home/circleci/build/public

  deploy_package:
    <<: *defaults
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: *login-to-registry
      - run:
          name: Release
          command: |
            npm run release -- --ci --no-increment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
        filters:
          context: deployments
          tags:
            only: /.*/
      - build_storybook:
          context: deployments
          requires:
            - test
      - build:
          context: deployments
          requires:
            - test
      - deploy_storybook:
          requires:
            - build_storybook
          context: deployments
          filters:
            branches:
              only:
                - master
      - deploy_package:
          requires:
            - build
          context: deployments
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
